spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 257774050
  jpa:
    show-sql: true

#端口配置
server:
    port: 25774

#支付宝配置
alipay:
  appId: 9021000163650226
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCV1RSBQ7TEMpCbtVpMCN3wDMIfzBooKuCoQnId8fakBO25T14qrxc8K2XxBd/5Ne2WxCPAyFCwb9aycwcJDwr/i3MWFLECsrKIPxeUdoZWtUZhOK1BvbLB4kuJl2tRNICrh7AJuJie3AT4zd0lw98MhcVGsu2ubT6As5Z0OTvSy452yQfL1R96hed4XJsxZI9SxkOOUfP1d7JrTWc3GCS4F7dC+ohfruSjUVGoxC4tkgMC7M481mPPmXaxNdAvcHVnhWz/wCk1i0pGVxRArnuzcaFkPSvBd0SExgXzHpkKSoW9jnCYM2gVBrRDKdo0RZXgdSwlrt8vHsW8ORk4FjvFAgMBAAECggEBAIZ3dK+N0+1AdAdJ+n/CdWu6B34B7neeA4D+IOw++tq4kaB9WkV0XaXiTNrCKv+9JjzoSi35mHC/7i64jNfUaEpvHBn09+cz+IXOGZtjw6yNg1w9QUB+vq7CKIiTG/0E4XUPkS0oPdBUJSIlnxMFdmgGpcWNT0H7SNy4T45+zvGd2lZoLpAR/A1mF2lQ9QVFmF0n4OyA403Rt+KQZX/7jMTaEp0xTmgPxsIFN0bLhxhgmWX1hXy8cIpckcK68r6NipqEeulHdYbjDF7XR8MMUvb+XebHvvlNhkZAPCUGBIFSb1k7RsDB6TI8pp3/af7kV36EWyEo5HbTL7/fOjcBYAECgYEA4ggXlKKla+HaIawO4vY4T3xbvdnvNJuuOnp3WBALKMD6P3QGY8dR0lcVNUUnLlRLP+GwSUo5g/kODnYVQlqc7cCwVJNR7LNZQL3CdeACW9b+cnDJmACofivAOgZjj0AIxX2tQUBpp5oPBRnauHxHKL06Ra4BTZb6Ne/sc3WWw6ECgYEAqbKm18GO6uTZS/+pg3xhU3beInJ/XudYWMrqW/b+cYR01bjuGnTax0llpWPhL+JL1pnKHn8AH+DLWrlC3PjCf2Yj1e0d4D3XJER0scMyS9wYjywdVi+fJGqLN9hi1NS+Dp1KnxBwJnx5Yv9b6S18PVn8Y++4r9HXgp9irgUYBaUCgYB7b8vg4gnQpqCHLv1aOPh7gABh57hYVISLbwHp16kgcnK3YFd0+g7W/bOZSdCh3mrR0iCBhcVvKv3gK+BkQjPdKxOgvGtLBo7Bal/eG51uJjUCrlGJbyKU9LOffIm2W1Pu9jk9nz2Tx/BX6sylX0lFGEHQd7xCcSbnecT5MMhKwQKBgFCLTQlnA3CWAlVCGbEg3gkBiFmNQstGvvYWCbpwt0AmAFZYmhrQj+669ZXUnFNf82L+R6LF4MdAqQR8njHHmHljf2rQSrfeYjkCjOi6nyrGYpnB9IKtw7lDIKT2/aHLABJrsblh0flSZ0MHtRYt0qREC7lbVKuOy91hzTKPlGFJAoGBALvkvhUlYhNHct+SADKip18EaVZhxe40OBZVZijnH3e9DzvqlsLRp5n7rZc0GTjY+6Kqycdy4DTDxw4usPdsovW0EDo7LvQo1wdvoTCT7aqvXJywLhInoa6mfuX3jsfrsykqGKdmQwHgAH3a2DgfrRMmUMrHtijVJnl9fpHoi0Ur
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuiJzohMZEXvqT0gvZp5uikw8SgKkEC2Iimtdsf60EhG0jtGoe+D8HSouLRWqDFYvOeCy4VTEygAInxWTlmaAwf4K/QgCcDO3REZWf/noQT8o/ZnyL/2Jm7mIQyOS7eekFiwsGTLGTxpDixC2kkd5o1saN9Q8KQNojw3wXf6wQkLY3l7LTUsucUoI86IokVatsrGTDmII1uFmpD+EMZIQKm3VqSBboNHIk4WMICqt301upaQpFn1wgg5CIpP4IFLlIgKnNGgO3KdWdTREbuxINE3pjlUNibtFFOnIxFOTFMTjO4ekwGXtLpxDTY4F69GIPoUbgcwJniZT2KkusQ9bSwIDAQAB
  notifyUrl: http://fb84e5fe.natappfree.cc/alipay/notify

